/**
 * Interface for a Starknet/Dojo contract abi
 *
 * NOTE the json import at the top of the file is from the `starknet`
 * libs as the abi generated by `soxo` is not a standard JSON format.
 */

import type { Contract } from "starknet";

export interface SysContract {
    /**
     * The name of the parsed system
     */
    c_name: string;
    /**
     * The Parsed contract
     */
    data: Contract;
}