/**
 * Interface for a Starknet/Dojo contract abi
 *
 * NOTE the json import at the top of the file is from the `starknet`
 * libs as the abi generated by `soxo` is not a standard JSON format.
 */

export interface SysAbi {
    /**
     * short form name
     */
    name: string;
    /**
     * The name of the parsed system
     */
    c_name: string;
    /**
     * The actual JSON object.
     */
    data: any;
    /**
     * The address of the contract
     */
    address: string;
}
